### ISSUE TITLE
Channels do not unsubscribe when the component unmounts

### ISSUE THREAD

**Issue by xavimb** [mayteio/use-pusher#11]
There's a missing line in the `useChannel` hook, inside the `useEffect` function. The function needs to return this:

```javscript
return () => client?.unsubscribe(channelName);
```

This way, then the channel name changes, the old channel gets unsubscribed. I tried this in a local copy and it worked. I would have made a PR but I couldn't get the project to build (most likely wrong typescript version or something like that) and I gave up.

**Comment by xavimb** [comment]
I forgot to say thanks for the library, it's been very helpful! 💯

**Comment by xavimb** [comment]
Ping @mayteio

**Comment by mayteio** [comment]
Hey @xavimb sorry for the delay. This has been added and released in 4.1.5.
