### ISSUE TITLE
Add react native example

### ISSUE THREAD

**Issue by mayteio** [mayteio/use-pusher#13]

**Comment by hsavit1** [comment]
should the pusher-mock library for testing work with react-native as well?

**Comment by mayteio** [comment]
Yes, `pusher-js-mock` is just a collection of ES6 classes so it should work when mocking pusher-js.

**Comment by hsavit1** [comment]
I've been having a bit of difficulty getting this working. I'll work on creating an example app, hopefully will have one by the end of the week

**Comment by mayteio** [comment]
As I mentioned, I only wrote Jest tests for this and didn't try it in a project. Please share when you can and I'll look into it. If you wanted to contribute too I would accept a pull request 🙃

**Comment by hsavit1** [comment]
Hey @mayteio , I made a small example project [here](https://github.com/hsavit1/react-native-use-pusher-example) - I'd be happy to expand on the example and open up a Pull Request on the use-pusher repo when it is working, but it's currently failing with the same error that I've seen in my personal project. See the below picture

![Screen Shot 2020-07-09 at 5 56 46 PM](https://user-images.githubusercontent.com/5156236/87094983-e4f75800-c20d-11ea-8e83-30c39fc53619.png)

Do you think you can help diagnose?

**Comment by mayteio** [comment]
Thanks mate. Obviously document doesn’t exist in rn so I wonder if the web version of pusher is being pulled in somewhere. I will clone and investigate when I jump online in about 1-2 hours for you.

**Comment by mayteio** [comment]
Hey @hsavit1 I can't get the react errors to show up nicely like that. I just get a blank white screen in the simulator and the error shows up as a one-liner with no line numbers in terminal.

Am I missing something to get the errors showing up like that?

![Screen Shot 2020-07-10 at 10 38 07 am](https://user-images.githubusercontent.com/43975092/87103831-73fd8200-c299-11ea-8aed-7f052ee90ce1.png)

I have opened #14 to track this.

**Comment by hsavit1** [comment]
> Hey @hsavit1 I can't get the react errors to show up nicely like that. I just get a blank white screen in the simulator and the error shows up as a one-liner with no line numbers in terminal.
> 
> Am I missing something to get the errors showing up like that?
> 
> 
> I have opened #14 to track this.

You're definitely experiencing the error, as you can see it in your console logs. To get the error to show, perhaps comment out the PusherProvider and hot reload. I
Then uncomment and hot reload again. I think the app needs to render properly first to get the redbox to show

**Comment by andrewschenk-linx** [comment]
src/PusherProvider.tsx
```
- import Pusher, { Options } from "pusher-js";
+ import Pusher, { Options } from "pusher-js/react-native";
```

When I use Pusher in a Class vs functional component, I import it from the second line.

**Comment by skulegirl** [comment]
I'm also encountering the same issue with "Can't find variable: document" error when running in React Native. I've correctly imported from "@harelpls/use-pusher/react-native"... I'm using expo, could that be responsible for the issue?

**Comment by mayteio** [comment]
@skulegirl no, not expo. `document` doesn't exist in the react-native environment. Frankly I'm not totally sure what's going on here. 

I've done a huge restructure in 7.0.0 to make sure there's no web packages in the native build and vice versa. I've also added a (working) example in `examples/native-use-pusher-example`. Check it out and let me know!

P.S. 7.0.0 uses pusher 7.0.0, which has some breaking changes.

Cheers!
