### ISSUE TITLE
Bind Connection using usePusher | React native

### ISSUE THREAD

**Issue by juandl** [mayteio/use-pusher#19]
Hi, I'm trying to get the status of the connection. using

```
 const { client } = usePusher();

 useEffect(() => {
    client.connection.bind('connected', () => {
      console.log('Realtime is go!');
    });
  }, []);
```

but it's not working, any way to do this?

**Comment by juandl** [comment]
I also try to use 

```
const { client } = usePusher();

useEvent(client.connection., 'connected', (data) =>  console.log('Realtime is go!'));

```

but it's not working too.

**Comment by mayteio** [comment]
Hey, first thing I notice is that client is missing from your dependancy array. On the first render, client will not be defined. Since client is stored in state though, when it becomes available it'll re-trigger the effect:
https://github.com/mayteio/use-pusher/blob/ea3b549d31ac17c901913ca8c9a935ad6fbfe3b9/src/core/PusherProvider.tsx#L40

If it still doesn't work, please provide a codesandbox and I can have a look!

**Comment by juandl** [comment]
@mayteio you are right, i wait for the "client" and is working. But in react native it's not working.

**Comment by mayteio** [comment]
That's great. Have you checked the rn example? https://github.com/mayteio/use-pusher/tree/master/examples/native-use-pusher-example

**Comment by juandl** [comment]
@mayteio yes I do, but it's not working, I try with 
-React navigation x5
-Expo (latest version)

I wrap the Provider with the navigation.. all the hooks work but in the case of getting the status of the connection, its not working

```
 const { client } = usePusher();

 useEffect(() => {
 if(client){
   client.connection.bind('connected', () => {
      console.log('Realtime is go!');
    });
  }
}, [client]);
```

**Comment by juandl** [comment]
Hi @mayteio , I found the solution, apparently passing the provider like this ist not working...

```
const Navigation = () => {
  return (
      <NavigationContainer>
          <Stack.Screen name='Home' component={HomePage} />
        </Stack.Navigator>
      </NavigationContainer>
  );
};
```
```
export default function App() {
  return (
   <PusherProvider {...config}>
          <Navigation />
   </PusherProvider>
  );
}
```

But passing directly to the NavigationContainer it's working: 

```
    <PusherProvider {...configPusher}>
      <NavigationContainer>
        <Stack.Navigator headerMode='none' initialRouteName='Landing'>
          <Stack.Screen name='Home' component={HomePage} />
        </Stack.Navigator>
      </NavigationContainer>
    </PusherProvider>
```

just leaving here for someone else :)

**Comment by mayteio** [comment]
Hey @juandl,

That's odd! Glad you could figure it out, cheers.
