### ISSUE TITLE
Update typescript types to accept metdata as 2nd argument in useEvent callback

### ISSUE THREAD

**Issue by Cubxity** [mayteio/use-pusher#20]
I propose that `useEvent` hook should add metadata in its callback type since authenticated channels send them with the event.

**Comment by mayteio** [comment]
I agree. I’ll add that in the next release!

**Comment by mayteio** [comment]
Hey @Cubxity this should work as it is, the types for the second callback are missing. You can use //@ts-ignore in the meantime if it throws an error.

I would like to update this, however, the pusher mock library we use needs to be updated to mock the metadata events. I can't write a test without updating that 😅. Definitely want to fix it though. I will leave this open until work lightens up and I can spend some time doing it!

**Comment by mayteio** [comment]
@Cubxity released in `7.1.0`
