### ISSUE TITLE
RNCNetInfo.getCurrentState got 3 arguments, expected 2

### ISSUE THREAD

**Issue by jigartankhupp** [mayteio/use-pusher#25]
### Platforms
Android

### Versions
"@react-native-community/netinfo": "3.2.1",
"react": "16.8.3",
"react-native": "0.59.9",
"@harelpls/use-pusher": "^7.0.0",

**Comment by mayteio** [comment]
Sounds like a problem with pusher-js based on the limited information you've provided (we don't do anything with NetInfo, just pass in a different pusher runtime), please post a question over there: https://github.com/pusher/pusher-js.
