### ISSUE TITLE
Having trouble retrieving all messages instantly

### ISSUE THREAD

**Issue by smakosh** [mayteio/use-pusher#27]
The issue I'm having is that I have to send 3 messages to finally see the first one I sent.

I have an example repo to reproduce the issue but it's private, I don't mind sharing access if it will help.

## Tools used
Next js and Next API routes

**Comment by mayteio** [comment]
Are you using client events or https trigger events? I very quickly learned that https events have a delay, and client events are the way to go in most cases (directly over wss).

**Comment by smakosh** [comment]
https trigger events

**Comment by smakosh** [comment]
I'm closing the issue as it's unrelated to the library.

**Comment by mayteio** [comment]
Cheers, good luck with it!
