### ISSUE TITLE
useEffect: data might not be optional in the callback

### ISSUE THREAD

**Issue by fromi** [mayteio/use-pusher#32]
Hi, thanks for the library, I am starting to integrate it and it look very promising!

In useEvent hook, the data parameter is currently optional in the callback: `callback: (data?: D, metadata?: { user_id: string }) => void`

Is there any specific reason for that?

**Comment by mayteio** [comment]
Not really, just so when you subscribe to events you don't *have* to take a data param. If it wasn't optional, this might happen:

```
const handleEvent = () = {}
useEvent("my-event", handleEvent) // TypeError: callback is missing data param
```

**Comment by fromi** [comment]
Hi @mayteio, I could not reproduce this error nor find any Typescript configuration that would produce it.

I'm ignoring parameters in callbacks all the time, for example with React Events. The event parameter is not optional, and not including it in the callback signature does not cause any trouble.
