### ISSUE TITLE
Maintaining connection in react-router

### ISSUE THREAD

**Issue by chr-ge** [mayteio/use-pusher#36]
Is it possible to maintain the same connection while navigating pages in react-router? 
For instance:
- User at `/join` route connects to presence channel and emits his name in a client event
- Then with react-router I `history.replace('/start-game')`.

I want the user to stay on the same connection because if I change route the user unsubscribes from the channel and I lose his name.

**Comment by mayteio** [comment]
I’d wrap your app in a context provider and make the connection there
instead of your deep component leafs. Let me know if you have troubles.

**Comment by chr-ge** [comment]
@mayteio How can I get the types to work (replace `any` in `LobbyContextInterface`)?
```tsx
interface GameContextInterface {
  channel: any | undefined;
  trigger: any | undefined;
}

const GameContext = createContext({} as GameContextInterface)

export const GameProvider = ({ children }: { children: React.ReactNode }) => {
  const channel = useChannel('presence-lobby-23')
  const trigger = useClientTrigger(channel)

  return (
    <GameContext.Provider value={{ channel, trigger }}>
      {children}
    </GameContext.Provider>
  )
}

export const useGameContext = () => useContext(GameContext)
```
