### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by madmod** [mayteio/use-pusher#5]
This module is really great. Is there any chance it could be made to support React Native? Maybe in PusherProvider it could use require and choose between `pusher-js` and `pusher-js/react-native`? Or you could pass in a custom Pusher and require `pusher-js` if one wasn't provided?

**Comment by mayteio** [comment]
Hey @madmod, glad you like it. I'd be happy to add RN support. I think following the convention of pusher is probably best, i.e. `import { PusherProvider } from "@harelpls/use-pusher/react-native"`.

In the meantime, you can pass your own value into the Provider like so:

```javascript
import React from 'react';
import Pusher from 'pusher-js/react-native'
import {PusherProvider} from '@harelpls/use-pusher'

export const NativePusherProvider = () => {
  // store it in state so if you need to listen for auth changes
  // you can reinitialise and resubscribe to channels
  const [client] = useState(new Pusher("key", {}));

  return <PusherProvider value={{client, triggerEndpoint: ""}} {...props} />
}
```

First class support would be ideal though. I'll stick it in the pipeline!

**Comment by mayteio** [comment]
Hey @madmod, I have started this - you can track progress on #7

**Comment by mayteio** [comment]
Thanks for your patience here! React native support has been released at 5.0.0.

**Comment by hsavit1** [comment]
great work @mayteio !

**Comment by mayteio** [comment]
Let me know how you go with it. I only wrote tests for it 🙃 didn’t use it in an actual example.
